import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

/// Provides localized strings throughout the app.
/// Usage: `final l10n = ref.watch(l10nProvider); l10n.home;`
final l10nProvider = Provider<AppLocalizations>((ref) {
  throw UnsupportedError('AppLocalizations must be provided via MaterialApp');
});

/// Localization delegate configuration for MaterialApp.
class AppLocalization {
  static const localizationsDelegates = [
    // AppLocalizations.delegate, // generated by flutter gen-l10n
    // GlobalMaterialLocalizations.delegate,
    // GlobalWidgetsLocalizations.delegate,
    // GlobalCupertinoLocalizations.delegate,
  ];

  static const supportedLocales = [
    Locale('en'),
    Locale('ja'),
  ];
}
